### ISSUE TITLE
lib/RestRes.js中res.send报错

### ISSUE THREAD

**Issue by yss** [DoubleSpout/rrestjs#3]
http.js:644
    throw new Error('Can\'t set headers after they are sent.');
          ^
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (http.js:644:11)
    at Function.tempobj.tempHeader (/Users/YSS/node_modules/rrestjs/lib/templateRender.js:22:6)
    at module.exports.cb (/Users/YSS/node_modules/rrestjs/lib/JadeRender.js:17:23)
    at module.exports.compiler (/Users/YSS/node_modules/rrestjs/lib/JadeRender.js:28:4)
    at tempobj.renderFile (/Users/YSS/node_modules/rrestjs/lib/templateRender.js:31:15)
    at fs.readFile (fs.js:176:14)
    at Object.oncomplete (fs.js:297:15)

因为直接调用了res.send()，在调用之前没有进行一次writeHeader

**Comment by yss** [comment]
it is my fault for not add 'return;' after res.direct().
sorry!
