### ISSUE TITLE
rrestjs --dev模式报错

### ISSUE THREAD

**Issue by jutleo** [DoubleSpout/rrestjs#41]
```
rrestjs process 8172 Checking config file starting...
rrestjs process 8172 Config file checking complete, errors:0/72, warns:0/72

events.js:72
    throw er; // Unhandled 'error' event
          ^
Error: listen EACCES
at errnoException (net.js:901:11)
at Server._listen2 (net.js:1020:19)
at listen (net.js:1061:10)
at Server.listen (net.js:1127:5)
at Object.<anonymous> (/Users/leo/nodes/test/app.js:7:5)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Function.Module.runMain (module.js:497:10)
```

**Comment by DoubleSpout** [comment]
listen EACCES 是端口无法监听的问题

**Comment by jutleo** [comment]
我修改了端口还是同样的错误，具体在哪里出的问题呢？

**Comment by dotku** [comment]
具体是在哪个文件改了端口呢？
